print('price generator')
print('')
name = input('product name: ')
prc = input('price:')
pro = input('provider: ')
hall = input('hall number: ')
exp = input('expiration: ')
lot = input('lot: ')
print('')
print('---------------------------------')
print('{:20}{}'.format('Name of product: ' ,name))
print('{:20}{}'.format('Price of product: ' ,prc))
print('{:20}{}'.format('Provider name: ' ,pro))
print('{:20}{}'.format('Hall: ' ,hall))
print('{:20}{}'.format('Time Expiration ' ,exp))
print('{:20}{}'.format('Number of lot: ' ,lot))